groups:
- name: cpu-usage
  rules:
  - alert: HighCPUUsage
    expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (pod) > 0.7
    for: 1m
    labels:
      severity: warning
    annotations:
      description: "CPU usage is above 70% for pod {{ $labels.pod }}"
