apiVersion: v1
kind: Service
metadata:
  name: my-c-service
spec:
  selector:
    app: my-c-service
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 8080  # Port used by the C service
  type: LoadBalancer  # Use a cloud provider’s load balancer
